export const beachdata = [
  {
    id: 1,
    cardImg: "cromer-beach.jpg",
    title: "cromer",
    seafront: 20,
    parking: true,
    restaurant: true,
    bars: true,
    location: "unknown",
    description: "lorem",
    tags: "norfolk norwich beach beaches cromer crabs",
  },
  {
    id: 2,
    cardImg: "holkham-beach.jpg",
    title: "holkham",
    seafront: 5,
    parking: true,
    restaurant: true,
    bars: true,
    location: "unknown",
    description: "lorem",
  },
  {
    id: 3,
    cardImg: "yarmouth-beach.jpg",
    title: "great yarmouth",
    seafront: 10,
    parking: true,
    restaurant: true,
    bars: true,
    location: "unknown",
    description: "lorem",
  },
  {
    id: 4,
    cardImg: "winterton-beach.jpg",
    title: "winterton on sea",
    seafront: 12,
    parking: true,
    restaurant: true,
    bars: true,
    location: "unknown",
    description: "lorem",
  },
  {
    id: 5,
    cardImg: "brancaster-beach.jpg",
    title: "brancaster",
    seafront: 7,
    parking: true,
    restaurant: true,
    bars: true,
    location: "unknown",
    description: "lorem",
  },
  {
    id: 6,
    cardImg: "hunstanton-beach.jpg",
    title: "hunstanton",
    seafront: 20,
    parking: true,
    restaurant: true,
    bars: true,
    location: "unknown",
    description: "lorem",
  },
  {
    id: 7,
    cardImg: "thornham-beach.jpg",
    title: "thornham",
    seafront: 20,
    parking: true,
    restaurant: true,
    bars: true,
    location: "unknown",
    description: "lorem",
  },
  {
    id: 8,
    cardImg: "wells-beach.jpg",
    title: "wells",
    seafront: 20,
    parking: true,
    restaurant: true,
    bars: true,
    location: "unknown",
    description: "lorem",
  },
  {
    id: 9,
    cardImg: "cley-beach.jpg",
    title: "cley",
    seafront: 20,
    parking: true,
    restaurant: true,
    bars: true,
    location: "unknown",
    description: "lorem",
  },
  {
    id: 10,
    cardImg: "sheringham-beach.jpg",
    title: "sheringham",
    seafront: 20,
    parking: true,
    restaurant: true,
    bars: true,
    location: "unknown",
    description: "lorem",
  },
  {
    id: 11,
    cardImg: "mundesley-beach.jpg",
    title: "mundesley",
    seafront: 20,
    parking: true,
    restaurant: true,
    bars: true,
    location: "unknown",
    description: "lorem",
  },
  {
    id: 12,
    cardImg: "seapalling-beach.jpg",
    title: "sea palling",
    seafront: 20,
    parking: true,
    restaurant: true,
    bars: true,
    location: "unknown",
    description: "lorem",
  },
];
