export const eventsdata = [
  {
    id: 1,
    eventImg: "autumn-lights-event.jpg",
    title: "autumn lights",
    location: "norfolk showground",
    date: "12th november 2022",
    booknow: true,
  },
  {
    id: 2,
    eventImg: "polar-express-event.jpg",
    title: "polar express",
    location: "north norfolk railway",
    date: "1st december 2022",
    booknow: true,
  },
  {
    id: 3,
    eventImg: "norwich-xmas-lights-event.jpg",
    title: "norwich xmas lights",
    location: "norwich city center",
    date: "21st november 2022",
    booknow: true,
  },
  {
    id: 4,
    eventImg: "prime-evil-event.jpg",
    title: "prime evil",
    location: "roar dinosuar park lenwade",
    date: "24th october 2022",
    booknow: true,
  },
  {
    id: 5,
    eventImg: "luminate-event.jpg",
    title: "luminate",
    location: "Sandringham Estate",
    date: "29th november 2022",
    booknow: true,
  },
  {
    id: 6,
    eventImg: "christmas-pantomime-event.jpg",
    title: "christmas-pantomime",
    location: "norwich theatre royal",
    date: "10th december 2022",
    booknow: true,
  },
  {
    id: 7,
    eventImg: "santas-grotto-event.jpg",
    title: "santa's grotto",
    location: "jarrolds norwich",
    date: "1st december 2022",
    booknow: true,
  },
  {
    id: 8,
    eventImg: "arctic-monkeys-live-event.jpg",
    title: "arctic monkeys live",
    location: "norwich city FC",
    date: "26th november 2022",
    booknow: true,
  },
];
